general:
  timeout: 10
  delay: 0.5
allow_tlds:
  # Allow common TLDs for typosquat detection
  # Empty list = allow all TLDs
  - .com
  - .net
  - .org
  - .gov
  - .edu
  - .co
  - .io
  - .info
  - .biz
  - .us
  - .uk
block_keywords:
  - parking
  - placeholder
